function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"P I X A R";
	window.questions = [		"WHAT YEAR WAS PIXAR ORIGINALLY ESTABLISHED", 
								"WHAT WAS PIXAR'S FIRST ANIMATED SHORT",
								"WHO IS HEAD OF PIXAR NOW", 
								"IN 1986 GEORGE LUCAS SOLD HIS COMPUTER DIVISION, TO WHOM DID GEORGE SELL TO", 
								"WHEN DID LUXO JR (THE DESK LAMP) FIRST APPEAR",
								"IN 1991 DISNEY AND PIXAR HAD AN AGREEMENT TO PRODUCE AND DISTRIBUTE THE FIRST FULL LENGTH COMPUTER GENERATED FILM. WHAT WAS THAT FILM",
								"IN 1998 WHAT WAS AWARDED BEST ANIMATED SHORT, IT WAS PLAYED BEFORE BUGS LIFE", 
								"WITH UPCOMMING FILMS TOY STORY 4 AND ON WARD UNDERWAY, HOW MANY FILMS AND ANIMATED SHORTS HAS PIXAR MADE",
								"PIXAR DOES REALLY WELL AT THE BOX OFFICE, ONE FILM RECENTLY BROKE ANOTHER RECORD. WHAT WAS THE FILM",
								"WHAT CITY IS PIXARS HEADQUARTERS LOCATED", ];
	window.correctAnswer = [ 	"D", "C", "A", "B", "E", "A", "C", "E", "D", "B" ]; 
	window.answerA = [ 			"1990", 
								"FOR THE BIRDS", 
								"JOHN LASSETER", 
								"ROBERT IGER", 
								"1995", 
								"TOY STORY",
								"MIKE'S NEW CAR",
								"20",
								"COCO",
								"OKLAND" ];
	window.answerB = [ 			"1970", 
								"KNICK KNACKS", 
								"CALVIN CLINE", 
								"STEVE JOBS",
								"2000",
								"MONSTERS INC",
								"ONE MAN BAND",
								"100",
								"MONSTERS UNIVERSITY",
								"EMERYVILLE" ];
	window.answerC = [ 			"1980",
								"THE ADVENTURES OF ANDRE AND WALLY B",
								"BILL GATES", 
								"MICHEAL EISNER", 
								"1999",
								"A BUGS LIFE",
								"GERI'S GAME",
								"30",
								"CARS 3",
								"SAN DEIGO" ];
	window.answerD = [ 			"1979",  
								"REDS DREAM",
								"ROBERT IGER", 
								"WALT DISNEY",
								"1985",
								"CARS",
								"FOR THE BIRDS",
								"60",
								"INCREDIBLES 2",
								"SAN ANTONIO" ];
	window.answerE = [ 			"1980", 
								"TIN TOY", 
								"OBAMA", 
								"ROY E. DISNEY", 
								"1986",
								"FINDING NEMO",
								"BOUNDIN",
								"82",
								"TOY STORY 3",
								"SAN FRANSICO" ];
	window.response = [ 		"PIXAR'S START WAS ACTUALLY ONCE CALLED THE GRAPHICS GROUP AND WAS PART OF GEORGE LUCAS'S PRODUCTION COMPANY WITH IN HIS COMPUTER DIVISION. GEORGE AND THE GRAPICS GROUP'S TASK WAS TO DEVELOPE A STATE OF THE ART COMPUTER TECH FOR THE FILM INDUSTRY", 
								"THE SHORT STARTED IN 1983 AND PREMIRED IN 1984. THE TECHNOLOGY USED TO CREATE THE SHORT WAS CONSIDERED TO BE GROUND BREAKING AT THE TIME. THOUGH PIXAR DIDN'T EXIST AT THE TIME IT IS STILL CONSIDERED THE FIRST SHORT", 
								"JOHN LASSETER WAS HIRED TO WORK ON THE ADVENTURES OF ANDRE AND WALLY B AND IN THE FALLOWING YEAR HE WAS HIRED AS FULL TIME MEMBER OF THE GRAPHICS GROUP AS AN INTER FACE DESIGNER", 
								"JOBS ESTABLISHED AN INDEPENDENT COMPANY AND PIXAR THAT THEN WAS INCORBERATED IN THE STATE OF CALIFORNIA THAT SAME YEAR, JOBS STAYED AS CEO UNTIL 2006", 
								"HE SHOWED UP IN AN ANIMATED SHORT FILM, AND IT WAS THE FIRST SHORT AFTER JOBS BOUGHT THE COMPUTER DIVISION. IT PREMIRED AT THE 1986 SIGGRAPH CONFRENCE AND LATER THE MASCOT TO THE COMPANIES LOGO",
								"LATER JOHN LASSETER WON A SPECIAL ACHEIVMENT AWARD FOR TOY STORY",
								"GERI SHOWED UP AS A SHORT THAT PLAYED BEFORE BUGS LIFE, PIXAR HAS CONTINUED TO SHOW SHORTS BEFORE THEIR FILMS EVER SINCE. BRING IT TO A NEW GENERATION OF PLAYING SHORTS BEFORE A FILM JUST LIKE IN THE 1930s",
								"PIXAR HASN'T SLOWED IT'S ROLL SINCE THE COMPANY CAME TO BEING, BRING CHARISHED MEMORIES FOR MANY FAMILYS IN THE PAST AND IN THE FUTURE",
								"INCREDIBLES 2 SHATTERED RECORDS AT THE BOX OFFICE WORLD WIDE TOTAL BEING 1.2 BILLION",
								"CHECK OUT THE STUDIO I'VE RECENTLY HEARD THEY'RE NO LONGER GIVING TOURS OF THE STUDIO BUT YOU CAN STAND AND LOOK AT THE GATES" ];
							
}
						